on:
    push:
        branches:
            - "*"

permissions: 
    contents: read
    packages: write

jobs:
    build-container-arm:
        name: "Build container images"
        runs-on: "ubuntu-latest"
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
      
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
      
            - name: Build
              uses: docker/build-push-action@v6
              with:
                platforms: linux/amd64 #,linux/arm64
                tags: ghcr.io/stujonesuk/iam-roles-anywhere-container:latest
                push: true
