on:
    push:
        branches:
            - "*"

permissions: 
    contents: read
    packages: write

jobs:
    build-container-arm:
        name: "Build ARM container image"
        runs-on: "ubuntu-24.04-arm"
        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
      
            - name: Build
              uses: docker/build-push-action@v6
              with:
                tags: ghcr.io/stujonesuk/iam-roles-anywhere-container:arm64
                push: true
    build-container-x64:
        name: "Build x64 container image"
        runs-on: "ubuntu-24.04"
        steps:
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
        
            - name: Build
              uses: docker/build-push-action@v6
              with:
                tags: ghcr.io/stujonesuk/iam-roles-anywhere-container:amd64
                push: true
            